from colorama import init, Fore, Style, Back
init()
import time
import sys
def dateam(hour, minute):
    print (Fore.WHITE + str(hour).zfill(2) + ":" + str(minute) + " AM", end= " ")
def datepm(hour, minute):
    print (Fore.WHITE + str(hour).zfill(2) + ":" + str(minute) + " PM", end= " ")
def waittime(n):
    time.sleep(n)
def choice(text):
    print(Fore.LIGHTBLUE_EX + text + Style.RESET_ALL)
    waittime(1)
def whichone():
    print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
def ui(text):
    print(Fore.MAGENTA + text + Style.RESET_ALL)
    waittime(1.5)

flashbattery=90

sophierel=7

markrel=8

m=4
n=54
def kevin(text):
    print (Fore.LIGHTYELLOW_EX + text + Style.RESET_ALL)
    waittime(1.5)
def mark(text):
    print (Fore.GREEN + text + Style.RESET_ALL)
    waittime(1.5)
def sophie(text):
    print(Fore.CYAN + text + Style.RESET_ALL)
    waittime(1.5)
def description(text):
    print(text)
    waittime(2)
def typegeneral(text, delay):
    for heytotta in text:
        print (heytotta, end= "")
        sys.stdout.flush()
        time.sleep(delay)
    print()
def typea(text, delay):
    datepm(m, n)
    for heytotta in text:
        print (Fore.GREEN + heytotta + Style.RESET_ALL, end= "")
        sys.stdout.flush()
        time.sleep(delay)
    print()
    waittime(1.0)

def typeb(text, delay):
    datepm(m, n)
    for heytotta in text:
        print (Fore.LIGHTYELLOW_EX + heytotta + Style.RESET_ALL, end= "")
        sys.stdout.flush()
        time.sleep(delay)
    print()
    waittime(1.0)    

def phase1(): 
    typea("sup k", 0.08)
    waittime(2)
    typeb("hey dude", 0.06)
    waittime(1.5)
    global n
    n= n +1
    typea("yo wanna hang out later ", 0.07)
    typeb("fck i should really study for mondays test", 0.05)
    typea("you kiddin right", 0.05)
    typeb("why?", 0.06)
    typea("what you mean why", 0.04)
    typea("you seriously gonna stay in on a saturday night", 0.04)
    waittime(3)
    typea("k?", 0.03)
    typeb("cmon man i can't study 150 pages in one day", 0.04)
    typea("yes you can, you already done thois", 0.06)
    waittime(2)
    typeb("sorry man, cant", 0.04)
    waittime(1)
    typea("ok you know what", 0.06)
    typea("you can stay home", 0.07)
    waittime(1)
    typea("ill just hang out by myself", 0.07)
    waittime(1)
    typea("alone", 0.08)
    waittime(1.5)
    typea ("probably gonna drink some beer", 0.07)
    waittime(1.5)
    typea("smoke a joint", 0.08)
    waittime(1.5)
    typea("maybe two", 0.04)
    typeb("fuck sake mark", 0.02)
    waittime(0.5)
    typea("yeah what", 0.06)
    typeb("let me study", 0.06)
    typea("hey, just put the phone away, I'm narrating my saturday night", 0.05)
    waittime(0.5)
    n=n+1
    typeb("to who", 0.06)
    typea("anyone who will listen to this poor, poor bastard", 0.05)
    waittime(0.5)
    typeb("fine", 0.07)
    waittime(0.5)
    typea("fine", 0.04)
    waittime(2.5)
    typea("yknow, was thinking", 0.06)
    waittime(1.3)
    typea("dyou think the pub's open tonight?", 0.06)
    typeb("FINE", 0.02)
    typeb("I'LL COME", 0.03)
    waittime(1)
    typea("awesome, knew you was cool", 0.06)
    waittime(2)
    typeb("you're bringing both beers and weed tho", 0.04)
    typea("who the fuck you think I am? fucking bill gates?", 0.06)
    waittime(1)
    typeb("fuck sake", 0.05)
    typeb("i'll bring beers", 0.08)
    waittime(1.8)
    typea("yknow, was thinking", 0.06)
    typeb("you do?", 0.03)
    typea("wow you're so funny fuck you", 0.03)
    waittime(1.0)
    typea("was saying, before you shithead comedian interrupted me", 0.04)
    typea("we could go to Sophie's and then to the haunted house in the suburbs", 0.05)
    waittime(1.2)
    typeb("the what", 0.06)
    waittime(0.5)
    typea("the haunted house", 0.06)
    typea("in the suburbs", 0.06)
    waittime(2.0)
    n=n+1
    typeb("?", 0.05)
    waittime(1)
    typea("wait", 0.05)
    typea("you're telling me", 0.06)
    waittime(0.5)
    typea("you never been to the haunted house", 0.07)
    typeb("no? i'm not a weirdo, yknow", 0.06)
    waittime(0.7)
    typea("fuck you k yes you are", 0.03)
    typeb("no im not you are", 0.04)
    typea("no you are", 0.03)
    waittime(0.5)
    typeb("man im telling you", 0.03)
    typeb("you are", 0.03)
    typea("no you", 0.02)
    typeb("DUDE", 0.04)
    waittime(0.9)
    typea("what?", 0.06)
    waittime(0.7)
    typea("fine", 0.06)
    waittime(1)
    typea("10:00 at sophies, weirdo", 0.07)
    waittime(2)
    typea("bring beer", 0.06)
    waittime(1.7)
    typea("and a flashlight", 0.05)
    waittime(2.0)
    typeb("a what", 0.08)
    waittime(2.4)
    typeb("Mark?", 0.07)
    print("----------------------------------------------------------------")

def phase2():
    waittime(2)
    print("You check your phone.")
    waittime(1)
    print("9:55 PM")
    waittime(1)
    print("You scream and throw the book on the bed while you stand up and search for the backpack.")
    waittime(2)
    print(Fore.LIGHTBLUE_EX + "1 - Under your bed\n2 - In the closet")
    while 1:
        print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
        searchbp=int(input(""))
        if searchbp==1:
            waittime(1)
            print("There it is")
            break
        elif searchbp==2:
            waittime(1)
            print("Why the fuck would you put your backpack in the closet?")
        else :
            print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
    waittime(1)
    print("You take your half-full water bottle, the flashlight, your camera, your textbook and place everything in the backpack.")
    waittime(1.2)
    print("You run out of your room and take your coat.")
    waittime(1.5)
    print(Fore.LIGHTMAGENTA_EX + "Hey Kevin")
    waittime(.7)
    kevin("Yeah ma'")
    waittime(1)
    print(Fore.LIGHTMAGENTA_EX + "You goin out?")
    waittime(.6)
    kevin("Yeah")
    waittime(1)
    print(Fore.LIGHTMAGENTA_EX + "Don't be lat-" + Style.RESET_ALL)
    print("You close the door behind you and run to the garage.")
    waittime(1.5)
    print("There is your blue bike and your father's red one")
    print(Fore.LIGHTBLUE_EX + "1 - Blue bike\n2 - Red bike")
    while 1:
        print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
        global bike
        bike=int(input(""))
        if bike==1:
            waittime(1)
            print("You take your bike")
            break
        elif bike==2:
            waittime(1)
            print("You take your father's bike")
            break
        else :
            print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
    typegeneral(". . .", 1)
    if bike==2:
        kevin("FUCK")
        waittime(1)
        print("Your father's bike breaks down as you go and you nearly break your neck")
        typegeneral(". . .", 1)
        print("10:15 PM")
    else:
        print("10:05 PM")
    waittime(.6)
    print("You knock on Sophie's door")
    waittime(5)
    print("You knock again")
def phase3():
    waittime(2)
    description("A familiar 1.84-meters-tall guy opens the door.")
    mark("Well look who it is")
    sophie("Is it Kev?")
    mark("Ya")
    print("You enter Sophie's house and a spicy smell fills your nose.")
    if bike==1:
        kevin("Sorry guys, I wasn't looking at the time")
    if bike==2:
        kevin("Sorry guys, my father's bike broke down and I had to walk")
    mark("Yeah man we were worried")
    description("You look at Mark with a very diffident look.")
    waittime(1.4)
    mark("We thought you were hittin' the books and forgot about us")
    kevin("Yeah well fuck you weirdo")
    sophie("Hey guys, chill")
    mark("Yeah whatever")
    waittime(1.2)
    description("You look around.")
    description("There are two empty beer bottle on the floor and the rests of a joint in the ashtray.")
    waittime(1)
    kevin("You already smoked one")
    mark("And you didn't bring the beer")
    description("You instinctively close your eyes and throw your head back.")
    kevin("Fuck sorry, you're right")
    sophie("Don't worry Kev, it's okay")
    mark("Yeah Kev, it's okay")
    waittime(1)
    description("Mark jumps on the sofa and picks up a beer bottle.")
    waittime(2)
    kevin("So? This haunted house?")
    description("Mark almost spits all of the beer he had in his mouth and sits up on the sofa.")
    mark("YEAH! That's what I was tryna remember, Sophie")
    description("You look at Sophie and she gives you a puzzled look.")
    mark("You remember the haunted house next to the bowling place right?")
    sophie("Not sure I do")
    mark("C'mon, we went there once or twice some years ago")
    description("Sophie scratches her head.")
    waittime(2)
    description("All of a sudden, her eyes light up.")
    sophie("OH FUCK YEAH! THE HOMELESS ONE")
    description("You look at both of them, trying to understand something.")
    mark("The homeless on-FUCK AHAHAHAHAHAHAHA YEAH I REMEMBER THAT")
    waittime(1)
    kevin("Hey guys? Can I please have an explanation here?")
    mark("Nothing much, we went there once and a homeless man chased us")
    sophie("Yeah and he was screaming 'GO AWAY'.")
    mark("Yeah that was cool.")
    description("You look at him with clear disagreement and disappointment.")
    waittime(1.5)
    mark("So? We gonna go?")
    sophie("Yeah, why not.")
    kevin("Ugh, fine.")
    print("------------------------------------------------")
def phase4():
    typegeneral(". . .", 1)
    kevin("Hey Mark, you sure you can drive?")
    description("Mark stumbles reaching the car and looks at you.")
    mark("Why, you wanna drive?")
    sophie("You remember he doesn't have a licence right?")
    print(Fore.LIGHTBLUE_EX + "1 - Yes\n2 - No")
    while 1:
        print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
        answ1=int(input(""))
        if answ1==1:
            waittime(1)
            kevin("Yeah, why not.")
            sophie("Kev, you don't have a driving licence.")
            kevin("Yeah but that'll be better than Mark driving while stoned.")
            description("Mark lies down on the backseats while Sophie sits on the passenger side.")
            typegeneral(". . .", 1)
            kevin("So? Where exactly is this place?")
            sophie("You know where the bowling place is?")
            description("The sound of Mark snoring fills the car.")
            kevin("No, don't think so.")
            sophie("Uhm.")
            description("Sophie scratches her head.")
            sophie("Just do what I tell you.")
            typegeneral(". .", 1)
            sophie("Turn left now.")
            print(Fore.LIGHTBLUE_EX + "1 - Turn right\n2 - Turn left")
            while 1:
                print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
                answ2=int(input(""))
                if answ2==2:
                    waittime(1)
                    description("You keep following Sophie's directions.")
                    typegeneral(". . .", 1)
                    break
                elif answ2==1:
                    waittime(1)
                    sophie("Dude why did you turn right?")
                    waittime(1)
                    print(Fore.LIGHTBLUE_EX + "1 - Sorry, I panicked\n2 - Didn't feel like turning left")
                    while 1:
                        print(Fore.GREEN + "Which one do you choose? " + Style.RESET_ALL)
                        answ3=int(input(""))
                        if answ3==1:
                            waittime(1)
                            kevin("Sorry, I panicked.")
                            sophie("You sure? You alright?")
                            kevin("Yeah, I was focusing on the road too much, sorry.")
                            typegeneral(". . .", 1)
                            break
                        elif answ3==2:
                            waittime(1)
                            kevin("Didn't really feel like turning left.")
                            description("You see Mark moving from the rearview mirror.")
                            mark("Booya! Brutal!")
                            description("After saying this, Mark returns to sleep almost instantly")
                            sophie("What the fuck man.")
                            sophie("Do as you want.")
                            description("Sophie turns to the window.")
                            description("You drive randomly until you find the bowling place.")
                            global sophierel
                            sophierel-=1
                            print(Fore.MAGENTA + "*Your relationship value with Sophie has dropped by 1*")
                            print(Fore.MAGENTA + "Relationship value with Sophie: " + str(sophierel) + Style.RESET_ALL)
                            typegeneral(". .", 1)
                            break
                        else:
                            print (Fore.RED + "You must choose a valid option." + Style.RESET_ALL)
                    break
                else:
                     print (Fore.RED + "You must choose a valid option." + Style.RESET_ALL)
        elif answ1==2:
            waittime(1)
            kevin("No, that's your car, go ahead. Worst case scenario we die hitting a tree.")
            mark("As you wish.")
            description("You sit on the seats in the back while Sophie sits on the passenger side.")
            description("You watch out of the window for the whole time.")
            typegeneral(". . .", 1)
            break
        else:
            print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
            continue
        break
    description("You watch the place through the windshield. It's a pretty big but clearly abandoned house.")
    waittime(0.5)
    description("The garden has been neglected for a really long time and there still are some rusty tools laying around.")
    waittime(0.5)
    description("You get closer to the house staying on the driveway.")
    waittime(0.5)
    description("The car's lights illuminate the main entrance, a red door on top of a few steps.")
    waittime(0.5)
    description("The house is painted with a light yellow colour that has been ruined by the passage of time.")
    if answ1==1:
        description("You stop the car at the end of the driveway.")
        if answ2==2 or answ3==1:
            description("Sophie looks at you.")
            sophie("Your destination is on the left.")
            kevin("Is it too late to go back home?")
            sophie("Oh come on, don't be a wuss.")
            description("Sophie smiles at you and gets out of the car.")
            waittime(1)
            description("You wake up Mark by hitting him on his back.")
            mark("What?")
            kevin("We here.")
            mark("Where?")
            kevin("C'mon man just get out of the car.")
        elif answ3==2:
            description("Sophie looks at you and gets out of the car without a sound.")
            description("You wake up Mark by hitting him on his back.")
            mark("What?")
            kevin("We here")
            mark("Where?")
            kevin("C'mon man just get out of the car.")
    elif answ1==2:
        description("Mark stops the car at the end of the driveway.")
        mark("Ta-duh! Here we are guys.")
        sophie("Yep, just as I remembered it.")
        mark("Careful with the homeless people.")
        sophie("Oh come on.")
        description("The three of you get out of the car.")
    waittime(2)
def frontgarden():
    typegeneral(". . .", 1)
    description("The front garden looks as if it had been abandoned all of a sudden a thousand years ago.")
    waittime(0.7)
    description("There still are some gardening tools on the ground, partially covered by some wild plants.")
    waittime(0.7)
    description("It is made up by a small garden divided in the middle by the path that leads to the main entrance.")
    waittime(0.5)
    kevin("So? Where was this homeless man?")
    mark("Can't really remember")
    sophie("He was just laying around in the garden around here, don't know why")
    kevin("Yeah well, how did that story end?")
    mark("We just outran him")
    kevin("Coolio")
    description("You look around but can't see anything that draws you attention, apart from an ugly statue.")


def backgarden():
    typegeneral(". . .", 1)
    description("The garden on the back is bigger than you imagined.")
    description("You really can't see where it ends.")
    description("In the darkness you can see it's divided into four squares with a fountain in the centre of it.")
    kevin("Woah, that's amazing")
    sophie("Yeah")
    waittime(1.5)
    mark("Hey Sophie, remember when we kissed in the shed?")
    sophie("Oh God please shut up")
    mark("I'll take that as a yes")
    kevin("What shed?")
    sophie("Please don't encourage him")
    mark("The one down there")
    description("You try to see ahead but the darkness prevents you from doing so.")
    description("Do you want to use the flashlight?")
    ui("This will consume 10" +"%"+ " of the flashlight battery.")
    global flashbattery
    ui("Current flashlight percentage:" + str(flashbattery) + "%")
    choice("1 - Yes\n2 - No")
    while 1:
        whichone()
        global flash1
        flash1=int(input(""))
        if flash1==1:
            flashbattery-=10
            ui("Current flashlight battery percentage:" + str(flashbattery) + "%")
            description("You take the flashlight out of your backpack and turn it on")
            description("Into each of the four squares there are some dead leaves and some weeds.")
            description("You can see now that the fountain is just a really big plaster sculpture.")
            kevin("Hey is that Freud?")
            mark("Who is that?")
            description("You look at Mark with clear disappointment.")
            waittime(1)
            mark("Hey, you remembered to bring the flashlight but you didn't remember the beers")
            waittime(0.5)
            kevin("Shut up")
            mark("Just describing the situation here")
            description("You can see the shed now.")
            waittime(1)
            description("It looks like a regular wooden shed, slightly smaller than your own.")
            description("Do you want to take a look at the shed?")
            choice("1 - Yes\n2 - No")
            while 1:
                whichone()
                shed1=int(input(""))
                if shed1==1:
                    kevin("I'm going in.")
                    mark("Why? You wanna a kiss from the big handsome guy?")
                    description("You see Sophie slowly roll her eyes.")
                    kevin("Not even in a milion years.")
                    waittime(2)
                    description("You slowly push the wooden door and point the flashlight on the inside.")
                    description("The door opens with a squeaking sound.")
                    waittime(1.1)
                    description("Inside the shed you see nothing but some shelves with some gardening tool.")
                    waittime(1.1)
                    kevin("How could you kiss her in this shit ass place")
                    mark("Dunno man")
                    waittime(1.2)
                    mark("I was kinda horny")
                    kevin("God please shut up")
                    description("You shine the flashlight through the shelves but can't find anything valuable.")
                    waittime(2)
                    kevin("Please Mark let me get out of here, this place smells bad")
                    mark("You know, I can't remember if we even had sex here")
                    waittime(1)
                    description("You push yourself between Mark and the door and manage to get out of the shed.")
                    description("You walk through the garden and get closer to Sophie as you hear Mark doing something in the shed.")
                    waittime(1)
                    break
                elif shed1==2:
                    mark("You wanna take a tour of the shed where I probably had sex with Sophie?")
                    description("You hear Sophie grunting and see her astonished face.")
                    sophie("Man we didn't had sex in that shithole")
                    waittime(1)
                    mark("You know, I'm not really sure of that")
                    sophie("Ugh")
                    mark("Your loss man, I'm going in")
                    description("Mark takes your flashback, walks across the garden and opens the squeaking wooden door of the shed.")
                    waittime(1.5)
                    description("You turn to Sophie.")
                    break
                else:
                    print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
            global sophierel
            if sophierel==6:
                kevin("Hey, you still mad for that?")
                sophie("What?")
                kevin("The right left thing")
                sophie("Oh shut up")
                choice("1 - I'm sorry\n2 - Oh come on")
                while 1:
                    whichone()
                    gardensophie=int(input(""))
                    if gardensophie==1:
                        kevin("Listen I'm sorry")
                        sophie("Yeah whatever")
                        kevin("I'm serious")
                        sophie("Yeah sure Kev, it didn't bother me don't worry")
                        kevin("Come on Sophie, I thought it was something funny")
                        waittime(1)
                        sophie("You thought doing the opposite of what I told you to do was funny?")
                        waittime(1.5)
                        kevin("Well if you put it that way")
                        sophie("Kevin just")
                        sophie("Shut up")
                        break
                    elif gardensophie==2:
                        kevin("Oh, come on Sophie")
                        sophie("What? You never listen to what I say")
                        kevin("That's not true")
                        sophie("You always think you're better than everyone else and can't believe that you are wrong once in a while")
                        kevin("...")
                        waittime(1.2)
                        sophie("Yeah that's what I thought")
                        sophie("Just")
                        sophie("Leave me alone")
                        sophierel-=1
                        print(Fore.MAGENTA + "*Your relationship value with Sophie has dropped by 1*")
                        print(Fore.MAGENTA + "Relationship value with Sophie: " + str(sophierel) + Style.RESET_ALL)
                        break
                    else:
                        print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
            elif sophierel==7:
                kevin("Yknow, I still don't get how could you be with that guy")
                sophie("Please")
                sophie("Don't remind me that")
                kevin("I mean")
                kevin("I'm his friend and everything")
                kevin("And I know you")
                kevin("I just can't imagine what were you thinking")
                sophie("I don't either, it was a kind of a dark period, you should know it")
                kevin("Yeah, Josh and everything")
            else:
                print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
                continue
            waittime(1)
            mark("HEY GUYS")
            description("Both you and Sophie turn to the shed.")
            sophie("YEAH?")
            mark("COME HERE")
            kevin("Why?")
            waittime(2)
            description("Silence.")
            description("You and Sophie watch each other.")
            waittime(1)
            description("You notice an hint of worry in her eyes.")
            description("You give her a confused look as you start walking toward the shed.")
            typegeneral(". . .", 1)
            description("You stand in front of the shed door with your hand on the handle.")
            waittime(1.5)
            kevin("Hey Mark?")
            waittime(1.5)
            description("Silence, again.")
            description("You slowly turn the handle.")
            waittime(2)
            description("Before you could completely open the door, you hear a cluttering sound, followed by a ")
            mark("FUCK")
            kevin("Hi there Mark")
            mark("This fucking thing ruined everything")
            waittime(1)
            description("Mark comes out from the shed, with a lame mask on his face.")
            waittime(1)
            sophie("God you're so cliché")
            mark("Hey, I would've scared the living shit out of you hadn't it been for that.")
            waittime(1.5)
            kevin("Yeah sure weirdo")
            mark("Don't start battles you know you can't win, weirdo")
            kevin("You're the one wearing a weird ass mask")
            mark("Yeah but")
            waittime(2.5)
            mark("Shut up weirdo")
            sophie("Hey guys")
            mark("Yeah?")
            sophie("Why don't you both shut up?")
            mark("Whatever")
            

            break
            
        elif flash1==2:
            kevin("Yeah I can't really see anything")
            sophie("You're not missing anything, don't worry")
            waittime(1.5)
            mark("Hey Sophie")
            sophie("Yeah?")
            waittime(2)
            mark("I can't remember if we had sex in that shed")
            sophie("Oh god please shut up")
            mark("Cause I remember we kissed in there")
            sophie("Please please please")
            mark("But can't remember anything else")
            description("You act interested in a old wooden table while you listen to the wispered conversation.")
            sophie("I asked you not to bring that up Mark")
            waittime(1.4)
            mark("Yeah sorry, thought it was funny")
            waittime(1.2)
            sophie("Yeah")
            sophie("As usual")
            description("You see Sophie heading to the front garden.")
            waittime(1)
            description("She looks sad.")
            description("You give Mark a judgemental glare and follow Sophie.")
            break
        else:
            print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)

def phase5():
    typegeneral(". . .", 1)
    description("You look at the silent house.")
    mark("There it is, as bright and colorful as the last time I saw it")
    description("You roll your eyes")
    mark("What?")
    waittime(1.5)
    sophie("Hey guys, wanna take a look at the outside first?")
    mark("Yeah why not, let's go find some homeless")
    choice("1 - Front garden\n2 - Back garden")
    while 1:
        whichone()
        expl1=int(input(""))
        if expl1==1:
            frontgarden()
            mark("Hey, wanna check out the back?")
            kevin("Yeah, why not.")
            backgarden()
            break
        elif expl1==2:
            backgarden()
            if flash1==1:
                kevin("Anyway, there's not much left to see here, you guys wanna check the front?")
                sophie("Sure, why not")
                frontgarden()
            else:
                frontgarden()     
            break
        else:
            print (Fore.RED + "You must choose a valid option" + Style.RESET_ALL)
    typegeneral(". . .", 1)
    description("You look at your watch.")
    description("01:07 AM")
    kevin("That's weird")
    mark("What? You?")
    description("You once again look at Mark filled with disappointment")
    waittime(0.8)
    kevin("No, I didn't think it was this late")
    sophie("Why? What time is it?")
    kevin("One am")
    mark("WHAT")
    mark("MY MOM IS GONNA KILL ME")
    sophie("Yeah that's what I thought")
    description("The three of you run to the car and drive back home.") 
    typegeneral(". . .", 1)
    description("The drive back home is silent.")
    description("Mark is driving.")
    description("Sophie fell asleep on the passenger seat.")
    description("And you're just there.")
    description("In the back.")
    description("Looking out of the window.")
    description(Fore.LIGHTRED_EX + "And you're all alone with yourself." + Style.RESET_ALL)


        

def game():
    phase1()
    phase2()
    phase3()
    phase4()
    phase5()

game()





